inayo/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home')
]

saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import api
from . import views


urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^add/$',
        views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_edit, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/bulk_delete/',
        views.variants_bulk_delete, name='variant-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/$',
        views.stock_edit, name='product-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/stock/add/$',
        views.stock_edit, name='product-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='product-stock-delete'),
    url(r'^(?P<product_pk>[0-9]+)/stock/bulk_delete/',
        views.stock_bulk_delete, name='stock-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_edit, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),
    url('^(?P<product_pk>[0-9]+)/images/reorder/$',
        api.reorder_product_images, name='product-images-reorder'),
    url('^(?P<product_pk>[0-9]+)/images/upload/$',
        api.upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/add/$',
        views.attribute_edit, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),
]

saleor/product/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category')
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .dashboard.urls import urlpatterns as dashboard_urls


admin.autodiscover()

urlpatterns = [
    # url(r'^', include(core_urls)),
    url(r'^', include('inayo.urls')),
    url(r'^account/', include(registration_urls, namespace='registration')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    # url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^dashboard/', include('inayo.splashboard.urls', namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^selectable/', include('selectable.urls')),
    # url(r'^inayo/datacenter/', include('inayo.data_center.urls', namespace='inayo')),
    url(r'^medicine', include('inayo.data_center.medicine.urls', namespace='medicine')),
    url(r'^other_product', include('inayo.data_center.other_product.urls', namespace='other_product')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/product/views.py
from __future__ import unicode_literals

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_http_methods

from . import forms
from ...core.utils import get_paginator_items
from ...product.models import (Product, ProductAttribute, ProductImage,
                               ProductVariant, Stock)
from ..views import staff_member_required


@staff_member_required
def product_list(request):
    products = Product.objects.prefetch_related('images').select_subclasses()
    form = forms.ProductClassForm(request.POST or None)
    if form.is_valid():
        return redirect('dashboard:product-add')
    products = get_paginator_items(products, 30, request.GET.get('page'))
    ctx = {'form': form, 'products': products}
    return TemplateResponse(request, 'dashboard/product/list.html', ctx)


@staff_member_required
def product_create(request):
    product = Product()
    form = forms.ProductForm(request.POST or None, instance=product)
    if form.is_valid():
        product = form.save()
        msg = _('Added product %s') % product
        messages.success(request, msg)
        return redirect('dashboard:variant-add', product_pk=product.pk)
    ctx = {'product_form': form, 'product': product}
    return TemplateResponse(
        request, 'dashboard/product/product_form.html', ctx)


@staff_member_required
def product_edit(request, pk):
    product = get_object_or_404(
        Product.objects.select_subclasses().prefetch_related(
            'images', 'variants'), pk=pk)
    attributes = product.attributes.prefetch_related('values')
    images = product.images.all()
    variants = product.variants.select_subclasses()
    stock_items = Stock.objects.filter(
        variant__in=variants).select_related('variant')

    form = forms.ProductForm(request.POST or None, instance=product)
    variants_delete_form = forms.VariantBulkDeleteForm()
    stock_delete_form = forms.StockBulkDeleteForm()

    if form.is_valid():
        product = form.save()
        msg = _('Updated product %s') % product
        messages.success(request, msg)
        return redirect('dashboard:product-update', pk=product.pk)
    ctx = {'attributes': attributes, 'images': images, 'product_form': form,
           'product': product, 'stock_delete_form': stock_delete_form,
           'stock_items': stock_items, 'variants': variants,
           'variants_delete_form': variants_delete_form}
    return TemplateResponse(
        request, 'dashboard/product/product_form.html', ctx)


@staff_member_required
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        messages.success(request, _('Deleted product %s') % product)
        return redirect('dashboard:product-list')
    return TemplateResponse(
        request, 'dashboard/product/modal_product_confirm_delete.html',
        {'product': product})


@staff_member_required
def stock_edit(request, product_pk, stock_pk=None):
    product = get_object_or_404(Product, pk=product_pk)
    if stock_pk:
        stock = get_object_or_404(Stock, pk=stock_pk)
    else:
        stock = Stock()
    form = forms.StockForm(request.POST or None, instance=stock,
                           product=product)
    if form.is_valid():
        form.save()
        messages.success(request, _('Saved stock'))
        product_url = reverse(
            'dashboard:product-update', kwargs={'pk': product_pk})
        success_url = request.POST.get('success_url', product_url)
        if is_safe_url(success_url, request.get_host()):
            return redirect(success_url)
    ctx = {'form': form, 'product': product, 'stock': stock}
    return TemplateResponse(request, 'dashboard/product/stock_form.html', ctx)


@staff_member_required
def stock_delete(request, product_pk, stock_pk):
    product = get_object_or_404(Product, pk=product_pk)
    stock = get_object_or_404(Stock, pk=stock_pk)
    if request.method == 'POST':
        stock.delete()
        messages.success(request, _('Deleted stock'))
        success_url = request.POST['success_url']
        if is_safe_url(success_url, request.get_host()):
            return redirect(success_url)
    ctx = {'product': product, 'stock': stock}
    return TemplateResponse(
        request, 'dashboard/product/stock_confirm_delete.html', ctx)


@staff_member_required
@require_http_methods(['POST'])
def stock_bulk_delete(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    form = forms.StockBulkDeleteForm(request.POST)
    if form.is_valid():
        form.delete()
        success_url = request.POST['success_url']
        messages.success(request, _('Deleted stock'))
        if is_safe_url(success_url, request.get_host()):
            return redirect(success_url)
    return redirect('dashboard:product-update', pk=product.pk)


@staff_member_required
def product_image_edit(request, product_pk, img_pk=None):
    product = get_object_or_404(Product, pk=product_pk)
    if img_pk:
        product_image = get_object_or_404(product.images, pk=img_pk)
    else:
        product_image = ProductImage(product=product)
    form = forms.ProductImageForm(request.POST or None, request.FILES or None,
                                  instance=product_image)
    if form.is_valid():
        product_image = form.save()
        if img_pk:
            msg = _('Updated image %s') % product_image.image.name
        else:
            msg = _('Added image %s') % product_image.image.name
        messages.success(request, msg)
        success_url = request.POST['success_url']
        if is_safe_url(success_url, request.get_host()):
            return redirect(success_url)
    ctx = {'form': form, 'product': product, 'product_image': product_image}
    return TemplateResponse(
        request, 'dashboard/product/product_image_form.html', ctx)


@staff_member_required
def product_image_delete(request, product_pk, img_pk):
    product = get_object_or_404(Product, pk=product_pk)
    product_image = get_object_or_404(product.images, pk=img_pk)
    if request.method == 'POST':
        product_image.delete()
        messages.success(
            request, _('Deleted image %s') % product_image.image.name)
        success_url = request.POST['success_url']
        if is_safe_url(success_url, request.get_host()):
            return redirect(success_url)
    ctx = {'product': product, 'product_image': product_image}
    return TemplateResponse(
        request,
        'dashboard/product/modal_product_image_confirm_delete.html', ctx)


@staff_member_required
def variant_edit(request, product_pk, variant_pk=None):
    product = get_object_or_404(Product.objects.select_subclasses(),
                                pk=product_pk)
    form_initial = {}
    if variant_pk:
        variant = get_object_or_404(product.variants.select_subclasses(),
                                    pk=variant_pk)
    else:
        variant = ProductVariant(product=product)
    form = forms.ProductVariantForm(request.POST or None, instance=variant,
                                    initial=form_initial)
    attribute_form = forms.VariantAttributeForm(request.POST or None,
                                                instance=variant)
    if all([form.is_valid(), attribute_form.is_valid()]):
        form.save()
        attribute_form.save()
        if variant_pk:
            msg = _('Updated variant %s') % variant.name
        else:
            msg = _('Added variant %s') % variant.name
        messages.success(request, msg)
        success_url = request.POST['success_url']
        if is_safe_url(success_url, request.get_host()):
            return redirect(success_url)
    ctx = {'attribute_form': attribute_form, 'form': form, 'product': product,
           'variant': variant}
    return TemplateResponse(
        request, 'dashboard/product/variant_form.html', ctx)


@staff_member_required
def variant_delete(request, product_pk, variant_pk):
    product = get_object_or_404(Product, pk=product_pk)
    variant = get_object_or_404(product.variants, pk=variant_pk)
    is_only_variant = product.variants.count() == 1
    if request.method == 'POST':
        variant.delete()
        messages.success(request, _('Deleted variant %s') % variant.name)
        success_url = request.POST['success_url']
        if is_safe_url(success_url, request.get_host()):
            return redirect(success_url)
    ctx = {'is_only_variant': is_only_variant, 'product': product,
           'variant': variant}
    return TemplateResponse(
        request,
        'dashboard/product/modal_product_variant_confirm_delete.html', ctx)


@staff_member_required
@require_http_methods(['POST'])
def variants_bulk_delete(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    form = forms.VariantBulkDeleteForm(request.POST)
    if form.is_valid():
        form.delete()
        success_url = request.POST['success_url']
        messages.success(request, _('Deleted variants'))
        if is_safe_url(success_url, request.get_host()):
            return redirect(success_url)
    return redirect('dashboard:product-update', pk=product.pk)


@staff_member_required
def attribute_list(request):
    attributes = ProductAttribute.objects.prefetch_related('values')
    ctx = {'attributes': attributes}
    return TemplateResponse(request, 'dashboard/product/attributes/list.html',
                            ctx)


@staff_member_required
def attribute_edit(request, pk=None):
    if pk:
        attribute = get_object_or_404(ProductAttribute, pk=pk)
    else:
        attribute = ProductAttribute()
    form = forms.ProductAttributeForm(request.POST or None, instance=attribute)

saleor/product/views.py
from __future__ import unicode_literals

from django.http import HttpResponsePermanentRedirect
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from .forms import get_form_class_for_product
from .models import Product, Category
from ..cart import Cart
from ..core.utils import get_paginator_items


def product_details(request, slug, product_id):
    products = Product.objects.get_available_products().select_subclasses()
    products = products.prefetch_related('categories', 'images',
                                         'variants__stock',
                                         'variants__variant_images__image',
                                         'attributes__values')
    product = get_object_or_404(products, id=product_id)
    if product.get_slug() != slug:
        return HttpResponsePermanentRedirect(product.get_absolute_url())
    form_class = get_form_class_for_product(product)
    cart = Cart.for_session_cart(request.cart, discounts=request.discounts)
    form = form_class(cart=cart, product=product,
                      data=request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('cart:index')
    template_name = 'product/details_%s.html' % (
        type(product).__name__.lower(),)
    templates = [template_name, 'product/details.html']
    return TemplateResponse(
        request, templates,
        {'product': product, 'form': form})


def category_index(request, path, category_id):
    category = get_object_or_404(Category, id=category_id)
    children_categories = category.get_children()
    breadcrumbs = category.get_ancestors(include_self=True)
    actual_path = category.get_full_path()
    if actual_path != path:
        return redirect('product:category', permanent=True, path=actual_path,
                        category_id=category_id)
    products = category.products.get_available_products().select_subclasses()
    products = products.prefetch_related(
        'images', 'variants', 'variants__stock')
    products = get_paginator_items(
        products, settings.PAGINATE_BY, request.GET.get('page'))
    return TemplateResponse(
        request, 'category/index.html',
        {'products': products, 'category': category,
         'children_categories': children_categories,
         'breadcrumbs': breadcrumbs})

templates/dashboard/product/attributes/confirm_delete.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Delete attribute" %} - {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:product-attributes' %}" class="breadcrumbs--ellipsed-item">{% trans "Attributes" %}</a></li>
        <li><span class="breadcrumbs--ellipsed-item"><i class="mdi-navigation-chevron-right"></i> {% trans "Delete attribute" %}</span></li>
    </ul>
{% endblock %}

{% block content %}
    <p>{% trans "Are you sure you want to delete the following attribute?" %}</p>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <ul class="collection">
                <li class="collection-item">
                    {{ attribute }}
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col m6 l4 offset-m3 offset-l4 right-align">
                <a href="{% url 'dashboard:product-attributes' %}" class="btn-flat"><i class="mdi-content-clear"></i> {% trans "Cancel" %}</a>
                <button type="submit" class="btn materialize-red"><i class="mdi-action-delete"></i> {% trans "Delete" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/dashboard/product/attributes/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}{% if attribute.pk %}{{ attribute }}{% else %}{% trans 'Add new attribute' %}{% endif %} - {% trans "Attributes" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block header_menu %}
    {% url "dashboard:product-attributes" as url %}
    {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block header_extra %}
    {% if attribute.pk %}
    <a class="dropdown-button" href="#" data-activates="attribute-delete" data-constrainwidth="false">
        <i class="mdi-navigation-more-vert"></i>
    </a>
    <ul id="attribute-delete" class="dropdown-content">
        <li>
            <a class="modal-trigger-custom" href="#base-modal"
                data-href="{% url 'dashboard:product-attribute-delete' pk=attribute.pk %}">
                {% trans "Remove attribute" %}
            </a>
        </li>
    </ul>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:product-attributes' %}" class="breadcrumbs--ellipsed-item">{% trans "Attributes" %}</a></li>
        <li><span class="breadcrumbs--ellipsed-item">{% if attribute.pk %}{{ attribute }}{% else %}{% trans 'Add new attribute' %}{% endif %}</span></li>
    </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" id="form-attributes">
        <div class="row">
            <div class="col l8">
                <div class="row">
                    {% csrf_token %}
                    {{ form.display|materializecss }}
                    {{ form.name|materializecss }}
                </div>

                <h5>{% trans "Attribute values" %}</h5>
                {{ formset.management_form }}
                {{ formset.non_form_errors.as_ul }}
                <table id="formset" class="highlight">
                    {% for form in formset.forms %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th>{{ field.label|capfirst }}</th>
                                {% endfor %}
                            </tr>
                            </thead>
                        {% endif %}
                        <tr>
                            {% for field in form.visible_fields %}
                                <td{% if forloop.last %} class="center-align"{% endif %}>
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field|materializecss }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col l8 right-align">
                {% if attribute.pk %}
                    <button type="submit" class="btn">{% trans "Update" %}</button>
                {% else %}
                    <button type="submit" class="btn">{% trans "Create" %}</button>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

templates/dashboard/product/attributes/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}

{% block title %}{% trans "Attributes" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block header_extra %}
    <div class="fixed-action-btn">
        <a class="btn-fab btn-floating btn-large waves-effect waves-light teal"
            href="{% url 'dashboard:product-attribute-add' %}" title="{% trans "Add attribute" %}">
            <i class="mdi-content-add"></i>
        </a>
    </div>
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs">
        <li>{% trans "Attributes" %}</li>
    </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col s12">
            {% if attributes %}
                <ul class="collection list list--attributes">
                    {% for attribute in attributes %}
                        <li class="collection-item list-item list--attributes-item list-item--two-lines">
                            <a class="list-item-name" href="{% url 'dashboard:product-attribute-update' pk=attribute.pk %}">{{ attribute.display }}</a>

                            <p class="list-item-desc">
                                    {% for value in attribute.values.all %}
                                    {{ value }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </p>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>{% trans "No attributes found." %}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/dashboard/product/attributes/modal_confirm_delete.html
{% load i18n %}

<form action="{% url "dashboard:product-attribute-delete" pk=attribute.pk %}" method="post">
    {% csrf_token %}
    <div class="modal-content">
        <h5>{% trans "Are you sure?" %}</h5>

        <p>
            {% blocktrans %}You are about to delete an attribute <strong>{{ attribute }}</strong>.{% endblocktrans %}
        </p>
    </div>

    <div class="modal-footer">
        <button type="submit" class="modal-action btn-flat blue-text">{% trans "Delete" %}</button>
        <a href="#!" class="modal-action modal-close btn-flat blue-text">{% trans "Cancel" %}</a>
    </div>
</form>