inayo/splashboard/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^orders$', views.orders, name='orders'),
    url(r'^managers$', views.managers, name='managers'),
    url(r'^stores$', views.stores, name='stores'),
    url(r'^employees$', views.employees, name='employees'),
    # url(r'^(?P<pk>[0-9]+)/$', views.customer_details, name='customer-details')
]

inayo/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home')
]

saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .order.urls import urlpatterns as order_urls
from .payments.urls import urlpatterns as payments_urls
from .product.urls import urlpatterns as product_urls
from .discount.urls import urlpatterns as discount_urls
from .shipping.urls import urlpatterns as shipping_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^payments/', include(payments_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^shipping/', include(shipping_urls)),
]

saleor/order/urls.py
from django.conf.urls import url

from ..core import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^%s/$' % (TOKEN_PATTERN,), views.details, name='details'),
    url(r'^%s/payment/$' % (TOKEN_PATTERN,),
        views.payment, name='payment'),
    url(r'^%s/payment/(?P<variant>[-\w]+)/$' % (TOKEN_PATTERN,),
        views.start_payment, name='payment'),
    url(r'^%s/cancel-payment/$' % (TOKEN_PATTERN,), views.cancel_payment,
        name='cancel-payment')
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .dashboard.urls import urlpatterns as dashboard_urls


admin.autodiscover()

urlpatterns = [
    # url(r'^', include(core_urls)),
    url(r'^', include('inayo.urls')),
    url(r'^account/', include(registration_urls, namespace='registration')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    # url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^dashboard/', include('inayo.splashboard.urls', namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^selectable/', include('selectable.urls')),
    # url(r'^inayo/datacenter/', include('inayo.data_center.urls', namespace='inayo')),
    url(r'^medicine', include('inayo.data_center.medicine.urls', namespace='medicine')),
    url(r'^other_product', include('inayo.data_center.other_product.urls', namespace='other_product')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inayo/splashboard/models.py
from django.db import models

# Create your models here.

saleor/order/models.py
from __future__ import unicode_literals

from decimal import Decimal
from uuid import uuid4

import emailit.api
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible, smart_text
from django.utils.timezone import now
from django.utils.translation import pgettext_lazy
from django_prices.models import PriceField
from payments import PurchasedItem
from payments.models import BasePayment
from prices import Price, FixedDiscount
from satchless.item import ItemLine, ItemSet

from ..core.utils import build_absolute_uri
from ..discount.models import Voucher
# from ..product.models import Product, Stock
from ..userprofile.models import Address
from . import Status


class OrderManager(models.Manager):

    def recalculate_order(self, order):
        prices = [group.get_total() for group in order
                  if group.status != Status.CANCELLED]
        total_net = sum(p.net for p in prices)
        total_gross = sum(p.gross for p in prices)
        shipping = [group.shipping_price for group in order]
        if shipping:
            total_shipping = sum(shipping[1:], shipping[0])
        else:
            total_shipping = Price(0, currency=settings.DEFAULT_CURRENCY)
        total = Price(net=total_net, gross=total_gross,
                      currency=settings.DEFAULT_CURRENCY)
        total += total_shipping
        order.total = total
        order.save()


@python_2_unicode_compatible
class Order(models.Model, ItemSet):
    status = models.CharField(
        pgettext_lazy('Order field', 'order status'),
        max_length=32, choices=Status.CHOICES, default=Status.NEW)
    created = models.DateTimeField(
        pgettext_lazy('Order field', 'created'),
        default=now, editable=False)
    last_status_change = models.DateTimeField(
        pgettext_lazy('Order field', 'last status change'),
        default=now, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, related_name='orders',
        verbose_name=pgettext_lazy('Order field', 'user'))
    tracking_client_id = models.CharField(
        max_length=36, blank=True, editable=False)
    billing_address = models.ForeignKey(
        Address, related_name='+', editable=False)
    shipping_address = models.ForeignKey(
        Address, related_name='+', editable=False, null=True)
    anonymous_user_email = models.EmailField(
        blank=True, default='', editable=False)
    token = models.CharField(
        pgettext_lazy('Order field', 'token'), max_length=36, unique=True)
    total_net = PriceField(
        pgettext_lazy('Order field', 'total'),
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2,
        blank=True, null=True)
    total_tax = PriceField(
        pgettext_lazy('Order field', 'total'),
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2,
        blank=True, null=True)
    voucher = models.ForeignKey(
        Voucher, null=True, related_name='+', on_delete=models.SET_NULL)
    discount_amount = PriceField(
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2,
        blank=True, null=True)
    discount_name = models.CharField(max_length=255, default='', blank=True)

    objects = OrderManager()

    class Meta:
        ordering = ('-last_status_change',)

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = str(uuid4())
        return super(Order, self).save(*args, **kwargs)

    def change_status(self, status):
        if status != self.status:
            self.status = status
            self.save()
            self.history.create(status=status)

    def get_items(self):
        return OrderedItem.objects.filter(delivery_group__order=self)

    def is_fully_paid(self):
        total_paid = sum([payment.total for payment in
                          self.payments.filter(status='confirmed')], Decimal())
        total = self.get_total()
        return total_paid >= total.gross

    def get_user_email(self):
        if self.user:
            return self.user.email
        return self.anonymous_user_email

    def __iter__(self):
        return iter(self.groups.all())

    def __repr__(self):
        return '<Order #%r>' % (self.id,)

    def __str__(self):
        return '#%d' % (self.id, )

    @property
    def discount(self):
        return FixedDiscount(
            amount=self.discount_amount, name=self.discount_name)

    def get_total(self):
        return self.total

    @property
    def billing_full_name(self):
        return '%s %s' % (self.billing_first_name, self.billing_last_name)

    def get_absolute_url(self):
        return reverse('order:details', kwargs={'token': self.token})

    def get_delivery_total(self):
        return sum([group.shipping_price for group in self.groups.all()],
                   Price(0, currency=settings.DEFAULT_CURRENCY))

    def send_confirmation_email(self):
        email = self.get_user_email()
        payment_url = build_absolute_uri(
            reverse('order:details', kwargs={'token': self.token}))
        context = {'payment_url': payment_url}

        emailit.api.send_mail(email, context, 'order/emails/confirm_email')

    def get_last_payment_status(self):
        last_payment = self.payments.last()
        if last_payment:
            return last_payment.status

    def get_last_payment_status_display(self):
        last_payment = self.payments.last()
        if last_payment:
            return last_payment.get_status_display()

    def is_pre_authorized(self):
        return self.payments.filter(status='preauth').exists()

    def create_history_entry(self, comment='', status=None, user=None):
        if not status:
            status = self.status
        self.history.create(status=status, comment=comment, user=user)

    def is_shipping_required(self):
        return any(group.is_shipping_required() for group in self.groups.all())

    @property
    def total(self):
        if self.total_net is not None:
            gross = self.total_net.net + self.total_tax.gross
            return Price(net=self.total_net.net, gross=gross,
                         currency=settings.DEFAULT_CURRENCY)

    @total.setter
    def total(self, price):
        self.total_net = price
        self.total_tax = Price(price.tax, currency=price.currency)

    def get_subtotal_without_voucher(self):
        if self.get_items():
            return super(Order, self).get_total()
        return Price(net=0, currency=settings.DEFAULT_CURRENCY)

    def get_total_shipping(self):
        costs = [group.shipping_price for group in self]
        if costs:
            return sum(costs[1:], costs[0])
        return Price(net=0, currency=settings.DEFAULT_CURRENCY)

    def can_cancel(self):
        return self.status not in {Status.CANCELLED, Status.SHIPPED}


class DeliveryGroup(models.Model, ItemSet):
    status = models.CharField(
        pgettext_lazy('Delivery group field', 'delivery status'),
        max_length=32, default=Status.NEW, choices=Status.CHOICES)
    order = models.ForeignKey(Order, related_name='groups', editable=False)
    shipping_price = PriceField(
        pgettext_lazy('Delivery group field', 'shipping price'),
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=4,
        default=0, editable=False)
    shipping_method_name = models.CharField(
        max_length=255, null=True, default=None, blank=True, editable=False)
    tracking_number = models.CharField(max_length=255, default='', blank=True)
    last_updated = models.DateTimeField(null=True, auto_now=True)

    def __str__(self):
        return pgettext_lazy(
            'Delivery group str', 'Shipment #%s') % self.pk

    def __repr__(self):
        return '%s(%r)' % (self.__class__.__name__, list(self))

    def __iter__(self):
        if self.id:
            return iter(self.items.all())
        return super(DeliveryGroup, self).__iter__()

    @property
    def shipping_required(self):
        return self.shipping_method_name is not None

    def change_status(self, status):
        self.status = status
        self.save()

    def get_total(self, **kwargs):
        subtotal = super(DeliveryGroup, self).get_total(**kwargs)
        return subtotal + self.shipping_price

    def add_items_from_partition(self, partition):
        for item_line in partition:
            product_variant = item_line.product
            price = item_line.get_price_per_item()
            quantity = item_line.get_quantity()
            try:
                # unit_price_gross= variant['MRP']
                name = product_variant['Name']
            except:
                # unit_price_gross=variant['mrp']
                name = product_variant['brand_name']
            # import pdb; pdb.set_trace()
            # stock = product_variant.select_stockrecord(quantity)
            self.items.create(
                product=product_variant['_id'],
                quantity=quantity,
                unit_price_net=price.net,
                product_name=name)
                # product_sku=product_variant.sku,
                # unit_price_gross=price.gross)
                # stock=stock,
                # stock_location=stock.location if stock else None)
            # if stock:
            #     # allocate quantity to avoid overselling
            #     Stock.objects.allocate_stock(stock, quantity)

    def get_total_quantity(self):
        return sum([item.get_quantity() for item in self])

    def is_shipping_required(self):
        return self.shipping_required

    def can_ship(self):
        return self.is_shipping_required() and self.status == 'new'

    def can_cancel(self):
        return self.status != Status.CANCELLED

inayo/splashboard/forms.py
# from django import forms
#
# class CreateUserForm(forms.Form):
#     username = forms.CharField(max_length=30)
#     first_name = forms.CharField()
#     last_name = forms.CharField()
#     password1=forms.CharField(max_length=30,widget=forms.PasswordInput()) #render_value=False
#     password2=forms.CharField(max_length=30,widget=forms.PasswordInput())
#     email=forms.EmailField(required=False)
#
#     title = forms.ChoiceField(choices=TITLE_CHOICES)
#
#     def clean_username(self): # check if username dos not exist before
#         try:
#             User.objects.get(username=self.cleaned_data['username']) #get user from user model
#         except User.DoesNotExist :
#             return self.cleaned_data['username']
#
#         raise forms.ValidationError("this user exist already")
#
#
#     def clean(self): # check if password 1 and password2 match each other
#         if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:#check if both pass first validation
#             if self.cleaned_data['password1'] != self.cleaned_data['password2']: # check if they match each other
#                 raise forms.ValidationError("passwords dont match each other")
#
#         return self.cleaned_data
#
#
#     def save(self): # create new user
#         new_user=User.objects.create_user(self.cleaned_data['username'],
#                                           self.cleaned_data['email'],
#                                           self.cleaned_data['password1'])
#         new_user.first_name = self.cleaned_data['first_name']
#         new_user.last_name = self.cleaned_data['last_name']
#         new_user.save()
from django.db import models
from django.forms import ModelForm
from saleor.userprofile.models import User
from django.core.exceptions import NON_FIELD_ERRORS

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password','managed_by']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

saleor/dashboard/category/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from unidecode import unidecode

from ...product.models import Category


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.parent_pk = kwargs.pop('parent_pk')
        super(CategoryForm, self).__init__(*args, **kwargs)
        if self.instance.parent and self.instance.parent.hidden:
            self.fields['hidden'].widget.attrs['disabled'] = True

    class Meta:
        model = Category
        exclude = ['slug']

    def save(self, commit=True):
        self.instance.slug = slugify(unidecode(self.instance.name))
        if self.parent_pk:
            self.instance.parent = get_object_or_404(
                Category, pk=self.parent_pk)
        if self.instance.parent and self.instance.parent.hidden:
            self.instance.hidden = True
        super(CategoryForm, self).save(commit=commit)
        self.instance.set_hidden_descendants(self.cleaned_data['hidden'])
        return self.instance

saleor/dashboard/shipping/forms.py
from __future__ import unicode_literals

from django import forms
from django.forms import inlineformset_factory

from ...shipping.models import ShippingMethod, ShippingMethodCountry


class ShippingMethodForm(forms.ModelForm):

    class Meta:
        model = ShippingMethod
        exclude = []


ShippingMethodCountryFormSet = inlineformset_factory(
    ShippingMethod, ShippingMethodCountry, fields=['country_code', 'price'],
    can_delete=True, extra=2, min_num=1, validate_min=True)

templates/inayo/dashboard/base.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load gross from prices_i18n %}
<!--  load slice from shop %} -->
{% load staticfiles %}
{ load bootstrap_pagination from bootstrap3 %}

{% block title %}Inayo | Dashboard{% endblock %}

{% block breadcrumb %}
  <!-- <li>
    <a href="#">Home</a>
  </li>
  <li>
    <span> Dashboard</span>
  </li> -->
{% endblock breadcrumb %}

{% block content %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <!-- <link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css"
      rel="stylesheet" type="text/css" /> -->
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <div class="left side-menu">
      <div class="sidebar-inner slimscrollleft">
          <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
              <li class="text-muted menu-title">Navigation</li>
              {% block left_navigation %}
              {% if request.user.is_superuser %}
                <li class="has_sub">
                    <a href="{% url "dashboard:index" %}" class="waves-effect active"><i class="ti-home"></i> <span> Dashboard </span> </a>
                </li>
                <li class="has_sub">
                    <a href="{% url "dashboard:orders" %}" class="waves-effect"><i class="ti-shopping-cart"></i> <span> Orders </span> </a>
                </li>
                <li class="has_sub">
                    <a href="{% url "dashboard:managers" %}" class="waves-effect"><i class="ti-user"></i> <span> Managers </span> </a>
                </li>
                <li class="has_sub">
                    <a href="{% url "dashboard:stores" %}" class="waves-effect"><i class="md md-account-child"></i> <span> Stores </span> </a>
                </li>
                <li class="has_sub">
                    <a href="#" class="waves-effect"><i class="ti-menu-alt"></i> <span> Products </span> </a>
                </li>
              {% else %}
              <li class="has_sub">
                  <a href="{% url "dashboard:index" %}" class="waves-effect active"><i class="ti-home"></i> <span> Dashboard </span> </a>
              </li>
              <li class="has_sub">
                  <a href="{% url "dashboard:orders" %}" class="waves-effect"><i class="ti-shopping-cart"></i> <span> Orders </span> </a>
              </li>
              <li class="has_sub">
                  <a href="{% url "dashboard:managers" %}" class="waves-effect"><i class="ti-user"></i> <span> Managers </span> </a>
              </li>
              <li class="has_sub">
                  <a href="{% url "dashboard:employees" %}" class="waves-effect"><i class="md md-account-child"></i> <span> Employees </span> </a>
              </li>
              <li class="has_sub">
                  <a href="#" class="waves-effect"><i class="ti-menu-alt"></i> <span> Products </span> </a>
              </li>
              {% endif %}
              {% endblock left_navigation %}
            </ul>
          </div>
      </div>
    </div>
    {% block page_content %}
    {% endblock page_content %}
  {% endblock content %}
{% for item in orders %}
    { y:{{ item.created|date:"Y" }} , a:{{item.total_net.net}} }{% if not forloop.last %},{% endif %}
{% endfor %}

templates/inayo/dashboard/employees.html
<!DOCTYPE html>
{% extends "inayo/dashboard/base.html" %}
{% load i18n %}
{% load gross from prices_i18n %}
<!--  load slice from shop %} -->
{% load staticfiles %}

{% block title %}Inayo | Dashboard{% endblock %}

{% block breadcrumb %}
  <!-- <li>
    <a href="#">Home</a>
  </li>
  <li>
    <span> Dashboard</span>
  </li> -->
{% endblock breadcrumb %}
{% block left_navigation %}
{% if request.user.is_superuser %}
  <li class="has_sub">
      <a href="{% url "dashboard:index" %}" class="waves-effect"><i class="ti-home"></i> <span> Dashboard </span> </a>
  </li>
  <li class="has_sub">
      <a href="{% url "dashboard:orders" %}" class="waves-effect"><i class="ti-shopping-cart"></i> <span> Orders </span> </a>
  </li>
  <li class="has_sub">
      <a href="{% url "dashboard:managers" %}" class="waves-effect"><i class="ti-user"></i> <span> Managers </span> </a>
  </li>
  <li class="has_sub">
      <a href="{% url "dashboard:stores" %}" class="waves-effect"><i class="md md-account-child"></i> <span> Stores </span> </a>
  </li>
  <li class="has_sub">
      <a href="#" class="waves-effect"><i class="ti-menu-alt"></i> <span> Products </span> </a>
  </li>
{% else %}
<li class="has_sub">
    <a href="{% url "dashboard:index" %}" class="waves-effect"><i class="ti-home"></i> <span> Dashboard </span> </a>
</li>
<li class="has_sub">
    <a href="{% url "dashboard:orders" %}" class="waves-effect"><i class="ti-shopping-cart"></i> <span> Orders </span> </a>
</li>
<li class="has_sub">
    <a href="{% url "dashboard:managers" %}" class="waves-effect"><i class="ti-user"></i> <span> Managers </span> </a>
</li>
<li class="has_sub">
    <a href="{% url "dashboard:employees" %}" class="waves-effect active"><i class="md md-account-child"></i> <span> Employees </span> </a>
</li>
<li class="has_sub">
    <a href="#" class="waves-effect"><i class="ti-menu-alt"></i> <span> Products </span> </a>
</li>
{% endif %}
{% endblock left_navigation %}
{% block page_content %}
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <h4 class="page-title">Orders</h4><br>
                </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <div class="card-box">
                  <div class="table-responsive">
                            <table class="table table-actions-bar">
                              <thead>
                                  <tr>
                                    <tr>
                                        <th>
                                            {% trans "Email" %}
                                        </th>
                                    </tr>
                                  </tr>
                              </thead>

                              <tbody>
                                {% for emp in employees %}
                                    <tr>
                                        <td>
                                            {{ emp.email }}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                </div>

                </div> <!-- end col -->


            </div>





        </div> <!-- container -->

    </div> <!-- content -->
    <script>
        var resizefunc = [];
    </script>
{% endblock page_content %}

templates/inayo/dashboard/managers.html
<!DOCTYPE html>
{% extends "inayo/dashboard/base.html" %}
{% load i18n %}
{% load gross from prices_i18n %}
<!--  load slice from shop %} -->
{% load staticfiles %}
{ load bootstrap_pagination from bootstrap3 %}

{% block title %}Inayo | Dashboard{% endblock %}

{% block breadcrumb %}
  <!-- <li>
    <a href="#">Home</a>
  </li>
  <li>
    <span> Dashboard</span>
  </li> -->
{% endblock breadcrumb %}
{% block left_navigation %}
{% if request.user.is_superuser %}
  <li class="has_sub">
      <a href="{% url "dashboard:index" %}" class="waves-effect"><i class="ti-home"></i> <span> Dashboard </span> </a>
  </li>
  <li class="has_sub">
      <a href="{% url "dashboard:orders" %}" class="waves-effect"><i class="ti-shopping-cart"></i> <span> Orders </span> </a>
  </li>
  <li class="has_sub">
      <a href="{% url "dashboard:managers" %}" class="waves-effect active"><i class="ti-user"></i> <span> Managers </span> </a>
  </li>
  <li class="has_sub">
      <a href="{% url "dashboard:stores" %}" class="waves-effect"><i class="md md-account-child"></i> <span> Stores </span> </a>
  </li>
  <li class="has_sub">
      <a href="#" class="waves-effect"><i class="ti-menu-alt"></i> <span> Products </span> </a>
  </li>
{% else %}
<li class="has_sub">
    <a href="{% url "dashboard:index" %}" class="waves-effect active"><i class="ti-home"></i> <span> Dashboard </span> </a>
</li>
<li class="has_sub">
    <a href="{% url "dashboard:orders" %}" class="waves-effect"><i class="ti-shopping-cart"></i> <span> Orders </span> </a>
</li>
<li class="has_sub">
    <a href="{% url "dashboard:managers" %}" class="waves-effect active"><i class="ti-user"></i> <span> Managers </span> </a>
</li>
<li class="has_sub">
    <a href="{% url "dashboard:employees" %}" class="waves-effect"><i class="md md-account-child"></i> <span> Employees </span> </a>
</li>
<li class="has_sub">
    <a href="#" class="waves-effect"><i class="ti-menu-alt"></i> <span> Products </span> </a>
</li>
{% endif %}
{% endblock left_navigation %}
{% block page_content %}
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <h4 class="page-title">Managers</h4><br>
                </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <div class="card-box">
                  <div class="table-responsive">
                            <table class="table table-actions-bar">
                                <thead>
                                  <tr>
                                      <th>Managers</th>
                                      <th></th>
                                  </tr>
                                </thead>

                                <tbody>
                                  {% for item in managers %}
                                  <tr>
                                      <td>{{item}}</td>
                                      <td>
                                        <a href="#demo" class="btn btn-info btn-custom" data-toggle="collapse">Stores</a>
                                          <div id="demo" class="collapse">
                                            <ul class="list-group">
                                            {% for i in item.user_set.all %}
                                            <li class="list-group-item">{{ i.email }}</li>
                                            {% endfor %}
                                            </ul>
                                          </div>

                                      </td>
                                  </tr>
                                  {%endfor%}
                                </tbody>
                            </table>
                        </div>
                </div>

                </div> <!-- end col -->


            </div>





        </div> <!-- container -->

    </div> <!-- content -->

{% endblock page_content %}